=== SAP-samples/cloud-integration-flow/Recipes/for/pricefx-integration-adapter/Project-Source/pricefx-integration-adapter/pricefx-connector-commons/src/main/resources/schemas/upsert-user-input-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "UserUpsertRequest",
  "type": "array",
  "default": [],
  "items": {
    "type": "object",
    "required": [
      "loginName",
      "email"
    ],
    "properties": {
      "loginName": {
        "type": "string"
      },
      "email": {
        "type": "string"
      },
      "firstName": {
        "type": "string"
      },
      "lastName": {
        "type": "string"
      },
      "activated": {
        "type": "boolean"
      },
      "workflowEmailingActivated": {
        "type": "boolean"
      },
      "noSession": {
        "type": "boolean"
      },
      "requireTFA": {
        "type": "boolean"
      },
      "receiveAdminEmail": {
        "type": "boolean"
      },
      "ssoOnly": {
        "type": "boolean"
      },
      "additionalInfo1": {
        "type": "number"
      },
      "additionalInfo2": {
        "type": "number"
      },
      "additionalInfo3": {
        "type": "string"
      },
      "additionalInfo4": {
        "type": "string"
      },
      "wizardDashboardName": {
        "type": "string"
      },
      "emailLocale": {
        "type": "string"
      },
      "defaultUserGroupEdit": {
        "type": "string"
      },
      "defaultUserGroupViewDetails": {
        "type": "string"
      },
      "passwordExpiry": {
        "type": "string"
      },
      "productFilterCriteria": {
        "type": "object",
        "required": [
          "operator",
          "criteria"
        ],
        "properties": {
          "operator": {
            "type": "string",
            "description": "Filter operation - AND / OR",
            "default": "and"
          },
          "criteria": {
            "type": "array",
            "description": "List of filters",
            "items": {
              "type": "object",
              "description": "Filter",
              "required": [
                "fieldName",
                "operator"
              ],
              "properties": {
                "fieldName": {
                  "type": "string",
                  "description": "field name"
                },
                "operator": {
                  "type": "string",
                  "description": "operator - equals, greaterThan, lessThan"
                },
                "value": {
                  "type": "string",
                  "description": "value"
                }
              }
            }
          }
        }
      },
      "customerFilterCriteria": {
        "type": "object",
        "required": [
          "operator",
          "criteria"
        ],
        "properties": {
          "operator": {
            "type": "string",
            "description": "Filter operation - AND / OR",
            "default": "and"
          },
          "criteria": {
            "type": "array",
            "description": "List of filters",
            "items": {
              "type": "object",
              "description": "Filter",
              "required": [
                "fieldName",
                "operator"
              ],
              "properties": {
                "fieldName": {
                  "type": "string",
                  "description": "field name"
                },
                "operator": {
                  "type": "string",
                  "description": "operator - equals, greaterThan, lessThan"
                },
                "value": {
                  "type": "string",
                  "description": "value"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== SAP-samples/cloud-integration-flow/Recipes/for/pricefx-integration-adapter/Project-Source/pricefx-integration-adapter/pricefx-connector-commons/src/test/resources/upsert-user-request.json
[
  {
    "loginName": "USER",
    "email": "user@pricefx.com",
    "firstName": "user",
    "lastName": "user",
    "productFilterCriteria": {
      "operator": "and",
      "criteria": [
        {
          "operator": "notNull",
          "fieldName": "sku"
        }
      ]
    }
  },
  {
    "loginName": "USER2",
    "email": "user2@pricefx.com",
    "firstName": "user2",
    "lastName": "user2",
    "productFilterCriteria": {
      "operator": "and",
      "criteria": [
        {
          "operator": "notNull",
          "fieldName": "sku"
        }
      ]
    }
  }
]
