=== SAP-samples/cloud-integration-flow/Recipes/for/pricefx-integration-adapter/Project-Source/pricefx-integration-adapter/pricefx-connector-commons/src/main/resources/schemas/upsert-quote-input-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "QuoteUpsertRequest",
  "type": "object",
  "required": [
    "uniqueName"
  ],
  "properties": {
    "uniqueName": {
      "type": "string"
    },
    "label": {
      "type": "string"
    },
    "targetDate": {
      "type": "string"
    },
    "headerText": {
      "type": "string"
    },
    "inputs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "value": {
              "type": "string"
            },
            "valueObject": {
              "type": "object"
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    },
    "additionalInfo1": {
      "type": "number"
    },
    "additionalInfo2": {
      "type": "number"
    },
    "additionalInfo3": {
      "type": "string"
    },
    "additionalInfo4": {
      "type": "string"
    },
    "externalRef": {
      "type": "string"
    },
    "expiryDate": {
      "type": "string"
    },
    "lineItems": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "required": [
            "lineId",
            "inputs"
          ],
          "properties": {
            "lineId": {
              "type": "string"
            },
            "inputs": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    },
                    "valueObject": {
                      "type": "object"
                    }
                  },
                  "required": [
                    "name"
                  ]
                }
              ]
            }
          }
        }
      ]
    }
  }
}

=== SAP-samples/cloud-integration-flow/Recipes/for/pricefx-integration-adapter/Project-Source/pricefx-integration-adapter/pricefx-connector-commons/src/test/resources/update-lineitem-request.json
{
  "uniqueName": "P-24049",
  "headerText": "xxxxx",
  "inputs": [
    {
      "name": "headerQty",
      "value": 30
    }
  ],
  "lineItems": [
    {
      "lineId": "12345",
      "sku": "abc",
      "inputs": [
        {
          "name": "lineQty",
          "value": 40
        }
      ]
    }
  ]
}
